Repository MentosTeam/Mentos-Android, pull requests merged in 2022-01, with the labels that each got.

#12 #11 [feat] Navigation Util
  app/src/main/java/com/mentos/mentosandroid/util/NavigationUtil.kt
Labels: pull request

#14 #13 [layout] Bottom navi 아이콘 수정
  app/src/main/res/drawable-hdpi/ic_main_home.png
  app/src/main/res/drawable-hdpi/ic_main_profile.png
  app/src/main/res/drawable-hdpi/ic_main_search.png
  app/src/main/res/drawable-hdpi/ic_main_state.png
  app/src/main/res/drawable-mdpi/ic_main_home.png
  app/src/main/res/drawable-mdpi/ic_main_profile.png
  app/src/main/res/drawable-mdpi/ic_main_search.png
  app/src/main/res/drawable-mdpi/ic_main_state.png
  app/src/main/res/drawable-xhdpi/ic_main_home.png
  app/src/main/res/drawable-xhdpi/ic_main_profile.png
  app/src/main/res/drawable-xhdpi/ic_main_search.png
  app/src/main/res/drawable-xhdpi/ic_main_state.png
  app/src/main/res/drawable-xxhdpi/ic_main_home.png
  app/src/main/res/drawable-xxhdpi/ic_main_profile.png
  app/src/main/res/drawable-xxhdpi/ic_main_search.png
  app/src/main/res/drawable-xxhdpi/ic_main_state.png
  app/src/main/res/drawable-xxxhdpi/ic_main_home.png
  app/src/main/res/drawable-xxxhdpi/ic_main_profile.png
  app/src/main/res/drawable-xxxhdpi/ic_main_search.png
  app/src/main/res/drawable-xxxhdpi/ic_main_state.png
  app/src/main/res/drawable/layer_gray_stroke_oval_shadow.xml
  app/src/main/res/drawable/layer_main_bottom.xml
  app/src/main/res/drawable/shape_gray_stroke_8.xml
  app/src/main/res/drawable/shape_gray_stroke_top_20.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: pull request

#19 #18 [feat] 멘토스 찾기 Adapter, ViewModel
  app/src/main/java/com/mentos/mentosandroid/data/Search.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchViewModel.kt
  app/src/main/java/com/mentos/mentosandroid/util/KeyBoardUtil.kt
  app/src/main/res/drawable-hdpi/ic_search_comment.png
  app/src/main/res/drawable-hdpi/ic_search_photo.png
  app/src/main/res/drawable-hdpi/img_search_all_category.png
  app/src/main/res/drawable-mdpi/ic_search_comment.png
  app/src/main/res/drawable-mdpi/ic_search_photo.png
  app/src/main/res/drawable-mdpi/img_search_all_category.png
  app/src/main/res/drawable-xhdpi/ic_search_comment.png
  app/src/main/res/drawable-xhdpi/ic_search_photo.png
  app/src/main/res/drawable-xhdpi/img_search_all_category.png
  app/src/main/res/drawable-xxhdpi/ic_search_comment.png
  app/src/main/res/drawable-xxhdpi/ic_search_photo.png
  app/src/main/res/drawable-xxhdpi/img_search_all_category.png
  app/src/main/res/drawable-xxxhdpi/ic_search_comment.png
  app/src/main/res/drawable-xxxhdpi/ic_search_photo.png
  app/src/main/res/drawable-xxxhdpi/img_search_all_category.png
  app/src/main/res/drawable/selector_search_all_category.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search_list.xml
  app/src/main/res/values/strings.xml
Labels: pull request

#25 [layout] 멘토스 글 등록 레이아웃
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchCreateFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchFragment.kt
  app/src/main/java/com/mentos/mentosandroid/util/NavigationUtil.kt
  app/src/main/res/drawable-hdpi/ic_search_delete_photo.png
  app/src/main/res/drawable-hdpi/ic_search_new_photo.png
  app/src/main/res/drawable-hdpi/img_mentos_none_17.png
  app/src/main/res/drawable-mdpi/ic_search_delete_photo.png
  app/src/main/res/drawable-mdpi/ic_search_new_photo.png
  app/src/main/res/drawable-mdpi/img_mentos_none_17.png
  app/src/main/res/drawable-xhdpi/ic_search_delete_photo.png
  app/src/main/res/drawable-xhdpi/ic_search_new_photo.png
  app/src/main/res/drawable-xhdpi/img_mentos_none_17.png
  app/src/main/res/drawable-xxhdpi/ic_search_delete_photo.png
  app/src/main/res/drawable-xxhdpi/ic_search_new_photo.png
  app/src/main/res/drawable-xxhdpi/img_mentos_none_17.png
  app/src/main/res/drawable-xxxhdpi/ic_search_delete_photo.png
  app/src/main/res/drawable-xxxhdpi/ic_search_new_photo.png
  app/src/main/res/drawable-xxxhdpi/img_mentos_none_17.png
  app/src/main/res/drawable/shape_gray_2_stroke_20.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_create.xml
  app/src/main/res/layout/item_search_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: pull request

#31 #26 [layout] 멘토쓰 찾기 Detail 레이아웃
  app/src/main/java/com/mentos/mentosandroid/ui/main/MainActivity.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchCreateFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchDetaiDialogt.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchViewModel.kt
  app/src/main/java/com/mentos/mentosandroid/util/MediatorLiveDataUtil.kt
  app/src/main/res/drawable-hdpi/ic_search_detail_edit.png
  app/src/main/res/drawable-hdpi/ic_search_detail_x.png
  app/src/main/res/drawable-hdpi/ic_search_x.png
  app/src/main/res/drawable-mdpi/ic_search_detail_edit.png
  app/src/main/res/drawable-mdpi/ic_search_detail_x.png
  app/src/main/res/drawable-mdpi/ic_search_x.png
  app/src/main/res/drawable-xhdpi/ic_search_detail_edit.png
  app/src/main/res/drawable-xhdpi/ic_search_detail_x.png
  app/src/main/res/drawable-xhdpi/ic_search_x.png
  app/src/main/res/drawable-xxhdpi/ic_search_detail_edit.png
  app/src/main/res/drawable-xxhdpi/ic_search_detail_x.png
  app/src/main/res/drawable-xxhdpi/ic_search_x.png
  app/src/main/res/drawable-xxxhdpi/ic_search_detail_edit.png
  app/src/main/res/drawable-xxxhdpi/ic_search_detail_x.png
  app/src/main/res/drawable-xxxhdpi/ic_search_x.png
  app/src/main/res/drawable/shape_gray_2_stroke_top_20.xml
  app/src/main/res/layout/dialog_search_detail.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_create.xml
  app/src/main/res/layout/item_search_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: pull request

#33 #32 [feat] 멘토스 글 등록 갤러리 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchCreateFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_search_create.xml
Labels: pull request

#38 #37 [layout] 내 정보 Detail 레이아웃
  app/src/main/res/drawable/layer_tab_selected_gray_stroke_20.xml
  app/src/main/res/drawable/selector_profile_tab.xml
  app/src/main/res/drawable/shape_tab_selected_gray_stroke_20.xml
  app/src/main/res/layout/fragment_profile_mentee.xml
  app/src/main/res/layout/fragment_profile_mentor.xml
  app/src/main/res/layout/item_major_mentos.xml
  app/src/main/res/layout/item_profile_review.xml
  app/src/main/res/values/strings.xml
Labels: layout

#40 Gaeun
  app/build.gradle
  app/src/main/java/com/mentos/mentosandroid/data/Search.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchDetaiDialogt.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchViewModel.kt
  app/src/main/java/com/mentos/mentosandroid/util/MentosImgUtil.kt
  app/src/main/java/com/mentos/mentosandroid/util/SharedPreferenceController.kt
  app/src/main/res/drawable-hdpi/ic_bottom_chat.png
  app/src/main/res/drawable-hdpi/ic_bottom_start_mentoring.png
  app/src/main/res/drawable-hdpi/img_mentos_blue_41.png
  app/src/main/res/drawable-hdpi/img_mentos_gray_41.png
  app/src/main/res/drawable-hdpi/img_mentos_orange_41.png
  app/src/main/res/drawable-mdpi/ic_bottom_chat.png
  app/src/main/res/drawable-mdpi/ic_bottom_start_mentoring.png
  app/src/main/res/drawable-mdpi/img_mentos_blue_41.png
  app/src/main/res/drawable-mdpi/img_mentos_gray_41.png
  app/src/main/res/drawable-mdpi/img_mentos_orange_41.png
  app/src/main/res/drawable-xhdpi/ic_bottom_chat.png
  app/src/main/res/drawable-xhdpi/ic_bottom_start_mentoring.png
  app/src/main/res/drawable-xhdpi/img_mentos_blue_41.png
  app/src/main/res/drawable-xhdpi/img_mentos_gray_41.png
  app/src/main/res/drawable-xhdpi/img_mentos_orange_41.png
  app/src/main/res/drawable-xxhdpi/ic_bottom_chat.png
  app/src/main/res/drawable-xxhdpi/ic_bottom_start_mentoring.png
  app/src/main/res/drawable-xxhdpi/img_mentos_blue_41.png
  app/src/main/res/drawable-xxhdpi/img_mentos_gray_41.png
  app/src/main/res/drawable-xxhdpi/img_mentos_orange_41.png
  app/src/main/res/drawable-xxxhdpi/ic_bottom_chat.png
  app/src/main/res/drawable-xxxhdpi/ic_bottom_start_mentoring.png
  app/src/main/res/drawable-xxxhdpi/img_mentos_blue_41.png
  app/src/main/res/drawable-xxxhdpi/img_mentos_gray_41.png
  app/src/main/res/drawable-xxxhdpi/img_mentos_orange_41.png
  app/src/main/res/drawable/selector_bottom_sheet_change_stroke_color.xml
  app/src/main/res/drawable/shape_bottom_sheet_black_stroke_rectangle_20.xml
  app/src/main/res/drawable/shape_bottom_sheet_gray_stroke_rectangle_20.xml
  app/src/main/res/layout/dialog_search_detail.xml
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/item_major_mentos.xml
  app/src/main/res/layout/item_search_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: pull request

#43 #42 [feat] 내 정보 RVAdpater, ViewModel
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/mentos/mentosandroid/ui/home/MentorRVAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileBindingAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileMajorDetailRVAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileMajorRVAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileMenteeFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileMentorFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileMentosRVAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileReviewRVAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/mentos/mentosandroid/util/MentosCategoryUtil.kt
  app/src/main/java/com/mentos/mentosandroid/util/MentosImgUtil.kt
  app/src/main/res/layout/fragment_profile_mentee.xml
  app/src/main/res/layout/fragment_profile_mentor.xml
  app/src/main/res/layout/item_major_mentos.xml
  app/src/main/res/layout/item_mentos.xml
Labels: feat

#44 #41 [feat, layout] BottomSheetFrag -> MentosCategoryUtil
  app/src/main/java/com/mentos/mentosandroid/ui/mentoringstart/BottomSheetFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/mentoringstart/MentoringStart3Fragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchCreateFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchViewModel.kt
  app/src/main/java/com/mentos/mentosandroid/util/MentosCategoryDialog.kt
  app/src/main/java/com/mentos/mentosandroid/util/MentosCategoryUtil.kt
  app/src/main/res/drawable/selector_search_all_category.xml
  app/src/main/res/drawable/shape_black_fill_8.xml
  app/src/main/res/drawable/shape_black_stroke_20.xml
  app/src/main/res/drawable/shape_gray_fill_8.xml
  app/src/main/res/layout/dialog_mentos_category.xml
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/fragment_mentoring_start1.xml
  app/src/main/res/layout/fragment_mentoring_start2.xml
  app/src/main/res/layout/fragment_mentoring_start3.xml
  app/src/main/res/layout/fragment_mentoring_start4.xml
  app/src/main/res/layout/item_major_mentos.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: pull request

#46 #45 [feat] 멘토쓰 찾기(멘티ver.) Adpater연결, 멘토/멘티 프로필 조회 Fragment
  app/src/main/java/com/mentos/mentosandroid/ui/search/OneMenteeProfileFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/OneMentorProfileFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchDetaiDialogt.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchMenteeAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchMentorAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/search/SearchViewModel.kt
  app/src/main/res/layout/dialog_search_detail.xml
  app/src/main/res/layout/fragment_one_mentee_profile.xml
  app/src/main/res/layout/fragment_one_mentor_profile.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_home_profile.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: pull request

#48 #47 [feat, layout] 내가 쓴 글, 멘티들의 후기 xml, 멘티-멘토 홈 화면 변경, 멘티 홈 -> 글 상세보기
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/mentos/mentosandroid/ui/home/HomeFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/home/HomeViewModel.kt
  app/src/main/java/com/mentos/mentosandroid/ui/home/MentorRVAdapter.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/PostListFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ProfileMentorFragment.kt
  app/src/main/java/com/mentos/mentosandroid/ui/profile/ReviewListFragment.kt
  app/src/main/res/drawable-hdpi/ic_edit_10.png
  app/src/main/res/drawable-hdpi/ic_x_8.png
  app/src/main/res/drawable-mdpi/ic_edit_10.png
  app/src/main/res/drawable-mdpi/ic_x_8.png
  app/src/main/res/drawable-xhdpi/ic_edit_10.png
  app/src/main/res/drawable-xhdpi/ic_x_8.png
  app/src/main/res/drawable-xxhdpi/ic_edit_10.png
  app/src/main/res/drawable-xxhdpi/ic_x_8.png
  app/src/main/res/drawable-xxxhdpi/ic_edit_10.png
  app/src/main/res/drawable-xxxhdpi/ic_x_8.png
  app/src/main/res/drawable/shape_trans_stroke_bottom_20.xml
  app/src/main/res/layout/fragment_post_list.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_profile_mentor.xml
  app/src/main/res/layout/fragment_review_list.xml
  app/src/main/res/layout/item_home_mentor.xml
  app/src/main/res/layout/item_profile_review.xml
  app/src/main/res/layout/item_search_list.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: layout, feat
